# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PartiiService_pb2 as PartiiService__pb2


class TranscriptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SingleTranscribe = channel.stream_stream(
                '/partii.Transcription/SingleTranscribe',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.TranscriptionResult.FromString,
                )
        self.LiveTranscribe = channel.stream_stream(
                '/partii.Transcription/LiveTranscribe',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.TranscriptionResult.FromString,
                )
        self.GetAvailable = channel.unary_unary(
                '/partii.Transcription/GetAvailable',
                request_serializer=PartiiService__pb2.EmptyMsg.SerializeToString,
                response_deserializer=PartiiService__pb2.AvailableConnection.FromString,
                )
        self.GetBuildNumber = channel.unary_unary(
                '/partii.Transcription/GetBuildNumber',
                request_serializer=PartiiService__pb2.EmptyMsg.SerializeToString,
                response_deserializer=PartiiService__pb2.BuildNumber.FromString,
                )


class TranscriptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SingleTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuildNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SingleTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.SingleTranscribe,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.TranscriptionResult.SerializeToString,
            ),
            'LiveTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveTranscribe,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.TranscriptionResult.SerializeToString,
            ),
            'GetAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailable,
                    request_deserializer=PartiiService__pb2.EmptyMsg.FromString,
                    response_serializer=PartiiService__pb2.AvailableConnection.SerializeToString,
            ),
            'GetBuildNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuildNumber,
                    request_deserializer=PartiiService__pb2.EmptyMsg.FromString,
                    response_serializer=PartiiService__pb2.BuildNumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'partii.Transcription', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transcription(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SingleTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/SingleTranscribe',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.TranscriptionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LiveTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/LiveTranscribe',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.TranscriptionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/partii.Transcription/GetAvailable',
            PartiiService__pb2.EmptyMsg.SerializeToString,
            PartiiService__pb2.AvailableConnection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBuildNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/partii.Transcription/GetBuildNumber',
            PartiiService__pb2.EmptyMsg.SerializeToString,
            PartiiService__pb2.BuildNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
